<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>x10</string>
	</array>
	<key>name</key>
	<string>X10</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(assert|async|at|athome|ateach|atomic|break|case|catch|clocked|continue|def|default|do|else|finally|finish|for|goto|if|in|new|offer|operator|return|switch|throw|try|val|var|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|haszero|instanceof|isref)\b</string>
			<key>name</key>
			<string>keyword.operator.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(here|self|super|this)\b</string>
			<key>name</key>
			<string>variable.language.x10:</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|interface|struct|type)\b</string>
			<key>name</key>
			<string>entity.name.type.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(void)\b</string>
			<key>name</key>
			<string>storage.type.primitive.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|extends|final|implements|native|offers|private|property|protected|public|static|throws|transient)\b</string>
			<key>name</key>
			<string>storage.modifier.x10</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|package)\b</string>
			<key>name</key>
			<string>keyword.other.x10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.x10</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.x10</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.x10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentationx10</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.x10</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.x10</string>
	<key>uuid</key>
	<string>DA19E99C-8CFD-42FA-AB6E-13259E9E520C</string>
</dict>
</plist>
